version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
        XDEBUG_CONFIG: remote_host=192.168.0.25
        PHP_XDEBUG_ENABLED: 1

  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes_from:
      - app
    links:
      - app
    ports:
      - 8091:80

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes_from:
      - app
    working_dir: /var/www
